VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IFormula"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'
'    Copyright (c) 2014, Fumito Hamamura
'    All rights reserved.
'
'    Redistribution and use in source and binary forms, with or without
'    modification, are permitted provided that the following conditions are met:
'
'    1. Redistributions of source code must retain the above copyright notice,
'       this list of conditions and the following disclaimer.
'    2. Redistributions in binary form must reproduce the above copyright notice,
'       this list of conditions and the following disclaimer in the documentation
'       and/or other materials provided with the distribution.
'
'    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
'    ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
'    WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
'    DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR
'    ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
'    (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
'    LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
'    ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
'    (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
'    SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
'

Option Explicit

Public Sub Startup(ByRef m As FModel, _
    ByRef v0 As Variant, _
    ByRef v1 As Variant, _
    ByRef v2 As Variant, _
    ByRef v3 As Variant, _
    ByRef v4 As Variant, _
    ByRef v5 As Variant, _
    ByRef v6 As Variant, _
    ByRef v7 As Variant, _
    ByRef v8 As Variant, _
    ByRef v9 As Variant, _
    ByRef v10 As Variant)

End Sub

Public Sub Main(ByRef m As FModel, _
    ByRef v0 As Variant, _
    ByRef v1 As Variant, _
    ByRef v2 As Variant, _
    ByRef v3 As Variant, _
    ByRef v4 As Variant, _
    ByRef v5 As Variant, _
    ByRef v6 As Variant, _
    ByRef v7 As Variant, _
    ByRef v8 As Variant, _
    ByRef v9 As Variant, _
    ByRef v10 As Variant)

End Sub



